### ISSUE TITLE
KeyError: 'query_tok'

### ISSUE THREAD

**Issue by SeekPoint** [guotong1988/NL2SQL#1]
mldl@ub1604:~/ub16_prj/NL2SQL$ python train.py --ca
Loading from original dataset
Loading data from data/train.jsonl
Loading data from data/train.tables.jsonl
Loading data from data/dev.jsonl
Loading data from data/dev.tables.jsonl
Loading data from data/test.jsonl
Loading data from data/test.tables.jsonl
Loading word embedding from glove/glove.42B.300d.txt
Using fixed embedding
Using column attention on aggregator predicting
Using column attention on selection predicting
Using column attention on where predicting
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    val_sql_data, val_table_data, TRAIN_ENTRY)
  File "/home/mldl/ub16_prj/NL2SQL/sqlnet/utils.py", line 200, in epoch_acc
    q_seq, col_seq, col_num, ans_seq, query_seq, gt_cond_seq, raw_data = to_batch_seq(sql_data, table_data, perm, st, ed, ret_vis_data=True)
  File "/home/mldl/ub16_prj/NL2SQL/sqlnet/utils.py", line 113, in to_batch_seq
    query_seq.append(sql['query_tok'])
KeyError: 'query_tok'
mldl@ub1604:~/ub16_prj/NL2SQL$

**Comment by guotong1988** [comment]
have you preprocess the data?

**Comment by SeekPoint** [comment]
ub16hp@UB16HP:~/ub16_prj/NL2SQL$ python extract_vocab.py
Loading from original dataset
Loading data from data/train_tok.jsonl
Traceback (most recent call last):
  File "extract_vocab.py", line 21, in <module>
    load_dataset(0, use_small=USE_SMALL)
  File "/home/ub16hp/ub16_prj/NL2SQL/sqlnet/utils.py", line 41, in load_dataset
    'data/train_tok.tables.jsonl', use_small=use_small)
  File "/home/ub16hp/ub16_prj/NL2SQL/sqlnet/utils.py", line 18, in load_data
    with open(SQL_PATH) as inf:
IOError: [Errno 2] No such file or directory: 'data/train_tok.jsonl'
ub16hp@UB16HP:~/ub16_prj/NL2SQL$ 

cannot find ***_tok*** in the data.tar.gz in wikisql

**Comment by guotong1988** [comment]
Can not read your post.

**Comment by SeekPoint** [comment]
ub16hp@UB16HP:~/ub16_prj/NL2SQL$ python extract_vocab.py
Loading from re-split dataset
Loading data from data/train.jsonl
Loading data from data/train.tables.jsonl
Loading data from data/dev.jsonl
Loading data from data/dev.tables.jsonl
Loading data from data/test.jsonl
Loading data from data/test.tables.jsonl
Loading word embedding from glove/glove.42B.300d.txt
Length of word vocabulary: 1917494
Traceback (most recent call last):
  File "extract_vocab.py", line 39, in <module>
    for tok in sql['question_tok']:
KeyError: 'question_tok'
ub16hp@UB16HP:~/ub16_prj/NL2SQL$

**Comment by SeekPoint** [comment]
I figure it out.
